In [12]:
%cd "~/Skorch/src/MoNet/"

/home/myf/Skorch/src/MoNet


In [11]:
import torch
import torch.nn as nn
from MoNet import FuncModel as fn
import importlib
importlib.reload(fn)

ImportError: cannot import name 'FuncModel' from 'MoNet' (/home/myf/Skorch/src/MoNet/__init__.py)

In [1130]:
F=(dn.m([sorted,max])+dn.m()*sum)*min
# print(F)
F.p([6,3,8,2,5,1])

Module ( [6, 3, 8, 2, 5, 1]
Module ( [6, 3, 8, 2, 5, 1]
Module ( [6, 3, 8, 2, 5, 1]
  0 : @dup:sorted *id:23101317881600 ([6, 3, 8, 2, 5, 1],) > [1, 2, 3, 5, 6, 8]
  1 : @dup:max *id:23101317881312 ([1, 2, 3, 5, 6, 8],) > 8
)  > 8
  1 : @dup:sum *id:23101317881024 ([6, 3, 8, 2, 5, 1],) > 25
)  > [8, 25]
  1 : @dup:min *id:23101317880256 ([8, 25],) > 8
)  > 8


8

In [1131]:
(dn.m([abs,abs])+dn.m([abs,abs]))(-1)

[1, 1, 1]

In [1132]:
@dn.M.dup
def sum2(x):
    return sum(x)
sum2

@dup:sum2 *id:23101317882704

In [1133]:
A1=dn.M()*sum*abs+max
A2=dn.m([sum,abs])+min
A=A1*A2
A

SEQ>Module(
  (0): LIC>Module(
    (0): SEQ>Module(
      (0): @dup:sum *id:23101317884912
      (1): @dup:abs *id:23101318840864
    )
    (1): @dup:max *id:23101318847152
  )
  (1): SEQ>Module(
    (0): @dup:sum *id:23101318854016
    (1): @dup:abs *id:23101331040304
  )
  (2): @dup:min *id:23101317639104
)

In [1134]:
A1=dn.M([sum,abs])
A=dn.m([sum,abs])*A1
A

SEQ>Module(
  (0): @dup:sum *id:23101317882176
  (1): @dup:abs *id:23101317881648
  (2): @dup:sum *id:23101317876224
  (3): @dup:abs *id:23101317876176
)

In [1105]:
dn.M(call=sum)

sum>Module()

In [1106]:
F=(dn.m()*sum*abs+max)*min+max
print(F)
# F([1,2,3])

LIC>Module(
  (0): SEQ>Module(
    (0): LIC>Module(
      (0): SEQ>Module(
        (0): @dup:sum *id:23101326200016
        (1): @dup:abs *id:23101326199104
      )
      (1): @dup:max *id:23101326211392
    )
    (1): @dup:min *id:23101326206688
  )
  (1): @dup:max *id:23101348318224
)


In [427]:
((dn.x*dn.nn.Linear(10,10))*nn.Linear(10,1))*((dn.x*dn.nn.Linear(10,10))*nn.Linear(10,1))

SEQ>Module(
  (0): @dup:Linear(in_features=10, out_features=10, bias=True) *id:23101348321584
  (1): @dup:Linear(in_features=10, out_features=1, bias=True) *id:23101348320528
  (2): @dup:Linear(in_features=10, out_features=10, bias=True) *id:23101349076448
  (3): @dup:Linear(in_features=10, out_features=1, bias=True) *id:23101348319520
)

In [428]:
((dn.X*dn.nn.Linear(10,10))*nn.Linear(10,1))*((dn.X*dn.nn.Linear(10,10))*nn.Linear(10,1))

SEQ>Module(
  (0): @dup:Linear(in_features=10, out_features=10, bias=True) *id:23101348326768
  (1): @dup:Linear(in_features=10, out_features=1, bias=True) *id:23101348317744
  (2): @dup:Linear(in_features=10, out_features=10, bias=True) *id:23101348327920
  (3): @dup:Linear(in_features=10, out_features=1, bias=True) *id:23101348317120
)

In [1137]:
F=dn.X*nn.Linear(10,10)*nn.Linear(10,10)*nn.Linear(10,10)*nn.Linear(10,1)
print(F)
for i in range(20):
    print(F(dn.torch.randn(1,10)))

SEQ>Module(
  (0): @dup:Linear(in_features=10, out_features=10, bias=True) *id:23101316224848
  (1): @dup:Linear(in_features=10, out_features=10, bias=True) *id:23101316224128
  (2): @dup:Linear(in_features=10, out_features=10, bias=True) *id:23101316223264
  (3): @dup:Linear(in_features=10, out_features=1, bias=True) *id:23101316225280
)
tensor([[0.5000]], grad_fn=<AddmmBackward0>)
tensor([[0.5787]], grad_fn=<AddmmBackward0>)
tensor([[0.6104]], grad_fn=<AddmmBackward0>)
tensor([[0.6185]], grad_fn=<AddmmBackward0>)
tensor([[0.5445]], grad_fn=<AddmmBackward0>)
tensor([[0.5043]], grad_fn=<AddmmBackward0>)
tensor([[0.4414]], grad_fn=<AddmmBackward0>)
tensor([[0.5980]], grad_fn=<AddmmBackward0>)
tensor([[0.4936]], grad_fn=<AddmmBackward0>)
tensor([[0.3874]], grad_fn=<AddmmBackward0>)
tensor([[0.4294]], grad_fn=<AddmmBackward0>)
tensor([[0.4715]], grad_fn=<AddmmBackward0>)
tensor([[0.3539]], grad_fn=<AddmmBackward0>)
tensor([[0.4931]], grad_fn=<AddmmBackward0>)
tensor([[0.4239]], grad_fn=<A

In [1147]:
(dn.X*dn.nn.Linear(10,1)*dn.nn.Linear(10,1))*dn.X*dn.nn.Linear(10,1)*dn.nn.Linear(10,1)

SEQ>Module(
  (0): @dup:Linear(in_features=10, out_features=1, bias=True) *id:23101292963216
  (1): @dup:Linear(in_features=10, out_features=1, bias=True) *id:23101293260192
  (2): @dup:Linear(in_features=10, out_features=1, bias=True) *id:23101293258896
  (3): @dup:Linear(in_features=10, out_features=1, bias=True) *id:23101293251312
)